name: 'Run LLVM Pipeline'
description: 'Configure, Build, and Test LLVM'
inputs:
  os:
    description: 'Host OS'
    required: true
  cmake_args:
    description: 'CMake Arguments'
    required: false
  arch:
    description: 'Host arch'
    required: false
    default: 'amd64'

runs:
  using: 'node12'
  main: 'main.js'
